package org.example.enums;

public enum ProfileStep {
    ENTER_NAME, ENTER_PHONE, REG_DONE,Change_Language,SETTING,
    ENTER_BRITHDAY,ENTER_ABOUT, BRANCHES1, BRANCHES2, ORDER1, DOSTAVKA, MENU_ORDER, MENU_BRANCHES, ENTER_FEEDBACK
}
